// Code generated by MockGen. DO NOT EDIT.
// Source: ./daemon/container_daemon.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	pfmodel "github.com/pathfinder-cm/pathfinder-go-client/pfmodel"
	reflect "reflect"
)

// MockContainerDaemon is a mock of ContainerDaemon interface
type MockContainerDaemon struct {
	ctrl     *gomock.Controller
	recorder *MockContainerDaemonMockRecorder
}

// MockContainerDaemonMockRecorder is the mock recorder for MockContainerDaemon
type MockContainerDaemonMockRecorder struct {
	mock *MockContainerDaemon
}

// NewMockContainerDaemon creates a new mock instance
func NewMockContainerDaemon(ctrl *gomock.Controller) *MockContainerDaemon {
	mock := &MockContainerDaemon{ctrl: ctrl}
	mock.recorder = &MockContainerDaemonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockContainerDaemon) EXPECT() *MockContainerDaemonMockRecorder {
	return m.recorder
}

// ListContainers mocks base method
func (m *MockContainerDaemon) ListContainers() (*pfmodel.ContainerList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContainers")
	ret0, _ := ret[0].(*pfmodel.ContainerList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContainers indicates an expected call of ListContainers
func (mr *MockContainerDaemonMockRecorder) ListContainers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContainers", reflect.TypeOf((*MockContainerDaemon)(nil).ListContainers))
}

// CreateContainer mocks base method
func (m *MockContainerDaemon) CreateContainer(container pfmodel.Container) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", container)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateContainer indicates an expected call of CreateContainer
func (mr *MockContainerDaemonMockRecorder) CreateContainer(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockContainerDaemon)(nil).CreateContainer), container)
}

// DeleteContainer mocks base method
func (m *MockContainerDaemon) DeleteContainer(hostname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContainer", hostname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteContainer indicates an expected call of DeleteContainer
func (mr *MockContainerDaemonMockRecorder) DeleteContainer(hostname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContainer", reflect.TypeOf((*MockContainerDaemon)(nil).DeleteContainer), hostname)
}

// CreateContainerBootstrapScript mocks base method
func (m *MockContainerDaemon) CreateContainerBootstrapScript(container pfmodel.Container) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainerBootstrapScript", container)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainerBootstrapScript indicates an expected call of CreateContainerBootstrapScript
func (mr *MockContainerDaemonMockRecorder) CreateContainerBootstrapScript(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainerBootstrapScript", reflect.TypeOf((*MockContainerDaemon)(nil).CreateContainerBootstrapScript), container)
}

// ValidateAndBootstrapContainer mocks base method
func (m *MockContainerDaemon) ValidateAndBootstrapContainer(container pfmodel.Container) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndBootstrapContainer", container)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndBootstrapContainer indicates an expected call of ValidateAndBootstrapContainer
func (mr *MockContainerDaemonMockRecorder) ValidateAndBootstrapContainer(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndBootstrapContainer", reflect.TypeOf((*MockContainerDaemon)(nil).ValidateAndBootstrapContainer), container)
}

// MigrateContainer mocks base method
func (m *MockContainerDaemon) MigrateContainer(container pfmodel.Container) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateContainer", container)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MigrateContainer indicates an expected call of MigrateContainer
func (mr *MockContainerDaemonMockRecorder) MigrateContainer(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateContainer", reflect.TypeOf((*MockContainerDaemon)(nil).MigrateContainer), container)
}
